@startuml
Connect4 ..> YesNoDialogView
Connect4 ..> GameView
Connect4 : + play()

YesNoDialogView : - question
YesNoDialogView : - answer
YesNoDialogView : + read()
YesNoDialogView : + isAffirmative()
YesNoDialogView : + isNegative()

GameView : + play()
GameView *--> Game
GameView *--> PlayerView
GameView *--> BoardView

PlayerView : + putToken()

BoardView : + showBoard()

Game *--> Board
Game *--> Turn
Game *--> Checker
Game : + getBoard()
Game : + getPlayer()
Game : + changeTurn() {
Game : + addToken(token)
Game : + calculateRow(col)
Game : + isWinner()
Game : + isTied()

Board : - MIN_ROWS
Board : - MIN_COLUMNS
Board : + MAX_ROWS
Board : - MAX_COLUMNS
Board : - grid    
Board : + getCell(coordinate)
Board : + getRow(number)
Board : + calculateRow(col)
Board : + addToken(token)

Turn : - numberOfRounds
Turn : + MAX_TURNS
Turn : - PLAYERS
Turn : - getTurn()
Turn : + getPlayer()
Turn : + changeTurn()
Turn : + isFinished()

Checker : - currentToken
Checker : - TOKENS_CONNECTED_FOR_WIN
Checker : + setCurrentToken(token)
Checker : - isConnect4(direction, board)
Checker : + isWinner(board)
Checker ..> Direcition

Direcition *--> Coordinate
Direcition : + getDirection
Direcition : + getOppocite

Coordinate : - x
Coordinate : - y
Coordinate : + shift()

@enduml