@startuml
Connect4 ..> YesNoDialogView
Connect4 ..> GameView
Connect4 ..> GameModeView
Connect4 : + play()

GameModeView ..> PlayerView
GameModeView ..> CPU
GameModeView : + ask()

YesNoDialogView : - question
YesNoDialogView : - answer
YesNoDialogView : + read()
YesNoDialogView : + isAffirmative()
YesNoDialogView : + isNegative()

CPU : + readToken()
PlayerView : + readToken()

GameView : - players
GameView *--> Game
GameView : + play()
GameView : - showFinalMsg()
GameView *--> BoardView

BoardView : + showBoar()

Game *--> Board
Game *--> Turn
Game *--> Checker
Game : + getBoard()
Game : + getTurn()
Game : + getPlayer()
Game : + changeTurn() {
Game : + addToken(token)
Game : + calculateRow(col)
Game : + isWinner()
Game : + isTied()

Board : - MIN_ROWS
Board : - MIN_COLUMNS
Board : + MAX_ROWS
Board : - MAX_COLUMNS
Board : - grid    
Board : + getCell(coordinate)
Board : + getRow(number)
Board : + calculateRow(col)
Board : + addToken(token)

Turn : - numberOfRounds
Turn : + MAX_TURNS
Turn : - PLAYER_1
Turn : - PLAYER_2
Turn : + getPlayer()
Turn : + getTurns()
Turn : + getTurn()
Turn : + changeTurn()

Checker : - currentToken
Checker : - TOKENS_CONNECTED_FOR_WIN
Checker : + setCurrentToken(token)
Checker : - isConnect4(direction, board)
Checker : + isConnectedInVertical(board)
Checker : + isConnectedInHorizontal(board)
Checker : + isConnectedInDiagonalPrincipal(board)
Checker : + isConnectedInDiagonalSecond(board)
Checker ..> Direcition

Direcition *--> Coordinate
Direcition : + getDirection
Direcition : + getOppocite

Coordinate : - x
Coordinate : - y
Coordinate : + getNorth() 
Coordinate : + getSouth() 
Coordinate : + getEast() 
Coordinate : + getWest() 
Coordinate : + getNorthEast() 
Coordinate : + getSouthEast() 
Coordinate : + getSouthWest() 

@enduml