@startuml
Connect4View ..> YesNoDialogView
Connect4View ..> Game
Connect4View ..> GameView
Connect4View : + play()

YesNoDialogView : - question
YesNoDialogView : - answer
YesNoDialogView : + read()
YesNoDialogView : + isAffirmative()
YesNoDialogView : + isNegative()

GameView : - showResult()
GameView : + play()
GameView *--> PlayerView
GameView *--> BoardView

PlayerView : + putColor()

BoardView : + show()
BoardView ..> Coordinate

Game *--> Board
Game *--> Turn
Game : + getBoard()
Game : + getCurrentColor()
Game : + changeTurn() {
Game : + addColor(col)
Game : + isFullColumn(col)
Game : + isWinner()
Game : + isTied()

Board ..> Line
Board ..> Coordinate
Board : - cells
Board : - EMPTY_CELL
Board : - currentCoordinate
Board : - calculateRow(col)
Board : - isConnect4(line)
Board : + getColor(coordinate)
Board : + isFullColumn(col)
Board : + addColor(col, color)
Board : + isWinner()

Turn : - numberOfRounds
Turn : + MAX_TURNS
Turn : - COLORS
Turn : - getTurn()
Turn : + getCurrentColor()
Turn : + changeTurn()
Turn : + isFinished()

Line : + {static} LENGTH
Line *--> Coordinate
Line : - coordenates
Line : + get(ordinal)
Line : + displaceOne(direction)
Line ..> Direction

Direction : - row
Direction : - col
Direction : + getOppocite()
Direction : + {static} SOUTH
Direction : + {static} WEST
Direction : + {static} SOUTH_WEST
Direction : + {static} NORTH_WEST
Direction : + {static} VALUES

Coordinate : - row
Coordinate : - column
Coordinate : + getRow()
Coordinate : + getColumn()
Coordinate : + shift(direction)
Coordinate : + {static} NUMBER_ROWS
Coordinate : + {static} ROWS
Coordinate : + {static} NUMBER_COLUMNS
Coordinate : + {static} COLUMNS
Coordinate : + {static} isRowValid(row)
Coordinate : + {static} isColumnValid(column)
Coordinate <|--  Direction
Coordinate ..>  ClosedInterval

ClosedInterval : - min
ClosedInterval : - max
ClosedInterval : + isIncluded()

@enduml