@startuml instructionsActivity

start
repeat
  :insert Yellow;
  :insert Red;
repeat while (are there 3 Yellow's on board) is (no)) not (yes))
:insert Yellow;
while (checkIsConnect4Yellow?) is (no)
    :insert Red;
    if (checkIsConnect4Red) then (yes)
      stop
    else (no)
      if (run out of discs?) then (yes)
        stop
      else (no)
        :insert Yellow;
      endif
    endif
endwhile (yes)

stop

@enduml
