@startuml
'https://plantuml.com/class-diagram

class Connect4
class Board
class Goal
class Disc
class Player
class HollowSquare
class Coordinate
class Color
class Yellow
class Red
class Turn
class Horizontal
class Vertical
class Insert
class Diagonal

Connect4 *--> Board
Connect4 *--> "42" Disc
Connect4 *--> "2" Player
Connect4 *--> Turn

Player --> "21" Disc
Player *--> Color
Player ..> Turn
Disc *--> Color
Color <|-- Yellow
Color <|-- Red
Player --> Goal
Goal <|-- Horizontal
Goal <|-- Vertical
Goal <|-- Diagonal
Goal ..|> "4..21" Insert
Insert ..> HollowSquare: target
Insert ..> Disc: uses
Turn *-left-> Insert

Board *--> "6x7" HollowSquare
HollowSquare o..> "0..1" Disc
HollowSquare *--> Coordinate




@enduml